In [94]:
import math

import torch
import numpy as np
import pandas as pd

from sklearn import datasets

torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 2060'

In [38]:
x = torch.arange(12)
X = x.reshape(3, -1)

X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [37]:
X.numel(), len(X), X.shape[0], X.shape, X.size()

(12, 3, 3, torch.Size([3, 4]), torch.Size([3, 4]))

In [36]:
x[2], X[0], X[0, :], X[:, 2], X[0, 2]

(tensor(2),
 tensor([0, 1, 2, 3]),
 tensor([0, 1, 2, 3]),
 tensor([ 2,  6, 10]),
 tensor(2))

In [50]:
x.exp(), torch.exp(x), math.e**x

(tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
         4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04]),
 tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
         4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04]),
 tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
         4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04]))

In [55]:
x.exp() - x, x.exp() + x, x.exp() * x, x.exp() / x, x**2 / x

(tensor([1.0000e+00, 1.7183e+00, 5.3891e+00, 1.7086e+01, 5.0598e+01, 1.4341e+02,
         3.9743e+02, 1.0896e+03, 2.9730e+03, 8.0941e+03, 2.2016e+04, 5.9863e+04]),
 tensor([1.0000e+00, 3.7183e+00, 9.3891e+00, 2.3086e+01, 5.8598e+01, 1.5341e+02,
         4.0943e+02, 1.1036e+03, 2.9890e+03, 8.1121e+03, 2.2036e+04, 5.9885e+04]),
 tensor([0.0000e+00, 2.7183e+00, 1.4778e+01, 6.0257e+01, 2.1839e+02, 7.4207e+02,
         2.4206e+03, 7.6764e+03, 2.3848e+04, 7.2928e+04, 2.2026e+05, 6.5862e+05]),
 tensor([       inf, 2.7183e+00, 3.6945e+00, 6.6952e+00, 1.3650e+01, 2.9683e+01,
         6.7238e+01, 1.5666e+02, 3.7262e+02, 9.0034e+02, 2.2026e+03, 5.4431e+03]),
 tensor([nan,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]))

In [59]:
r = torch.randn(3, 4)
r[1:3, 1:3] = 0.5555
r

tensor([[ 1.0928,  2.3828,  1.4546,  0.0529],
        [-0.5365,  0.5555,  0.5555, -2.0102],
        [-1.0795,  0.5555,  0.5555, -0.1477]])

In [67]:
X + r, X * r

(tensor([[ 1.0928,  3.3828,  3.4546,  3.0529],
         [ 3.4635,  5.5555,  6.5555,  4.9898],
         [ 6.9205,  9.5555, 10.5555, 10.8523]]),
 tensor([[  0.0000,   2.3828,   2.9093,   0.1587],
         [ -2.1460,   2.7775,   3.3330, -14.0713],
         [ -8.6363,   4.9995,   5.5550,  -1.6247]]))

In [72]:
torch.concat([X, r], axis=0), torch.concat([X, r], axis=1)

(tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
         [ 4.0000,  5.0000,  6.0000,  7.0000],
         [ 8.0000,  9.0000, 10.0000, 11.0000],
         [ 1.0928,  2.3828,  1.4546,  0.0529],
         [-0.5365,  0.5555,  0.5555, -2.0102],
         [-1.0795,  0.5555,  0.5555, -0.1477]]),
 tensor([[ 0.0000,  1.0000,  2.0000,  3.0000,  1.0928,  2.3828,  1.4546,  0.0529],
         [ 4.0000,  5.0000,  6.0000,  7.0000, -0.5365,  0.5555,  0.5555, -2.0102],
         [ 8.0000,  9.0000, 10.0000, 11.0000, -1.0795,  0.5555,  0.5555, -0.1477]]))

In [73]:
X.sum(axis=0), X.sum(axis=1), X.sum()

(tensor([12, 15, 18, 21]), tensor([ 6, 22, 38]), tensor(66))

In [75]:
a = torch.arange(3)
b = torch.arange(3).reshape(3, 1)

a > b, a < b, a == b

(tensor([[False,  True,  True],
         [False, False,  True],
         [False, False, False]]),
 tensor([[False, False, False],
         [ True, False, False],
         [ True,  True, False]]),
 tensor([[ True, False, False],
         [False,  True, False],
         [False, False,  True]]))

In [77]:
print(id(X))
X = X + 0
print(id(X))
X[:] = X + 0
print(id(X))

139918555737984
139918554758944
139918554758944


In [80]:
X_np = X.numpy()
X[1, 1] = 99
X_np[2, 2] = 77

X_np, X

(array([[ 0,  1,  2,  3],
        [ 4, 99,  6,  7],
        [ 8,  9, 77, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4, 99,  6,  7],
         [ 8,  9, 77, 11]]))

In [ ]:
X_np = X.numpy()
X[1, 1] = 99
X_np[2, 2] = 77

X_np, X

(array([[ 0,  1,  2,  3],
        [ 4, 99,  6,  7],
        [ 8,  9, 77, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4, 99,  6,  7],
         [ 8,  9, 77, 11]]))

In [88]:
nx = np.arange(12)
t_n = torch.from_numpy(nx).to('cuda')

nx[4] = 99
t_n[5] = 77

t_n, nx

(tensor([ 0,  1,  2,  3,  4, 77,  6,  7,  8,  9, 10, 11], device='cuda:0'),
 array([ 0,  1,  2,  3, 99,  5,  6,  7,  8,  9, 10, 11]))

# Datasets

In [104]:
ds.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [105]:
ds = datasets.load_iris()

X = pd.DataFrame(data=ds.data, columns=ds.feature_names)
y = pd.DataFrame(data=ds.target, columns='target', dtype='category')
y.target

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
X = torch.tensor(df[.].to_numpy())