In [2]:
import math

import torch
import numpy as np
import pandas as pd

from sklearn import datasets

torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 2060'

In [3]:
x = torch.arange(12)
X = x.reshape(3, -1)

X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [4]:
X.numel(), len(X), X.shape[0], X.shape, X.size()

(12, 3, 3, torch.Size([3, 4]), torch.Size([3, 4]))

In [5]:
x[2], X[0], X[0, :], X[:, 2], X[0, 2]

(tensor(2),
 tensor([0, 1, 2, 3]),
 tensor([0, 1, 2, 3]),
 tensor([ 2,  6, 10]),
 tensor(2))

In [6]:
x.exp(), torch.exp(x), math.e**x

(tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
         4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04]),
 tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
         4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04]),
 tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
         4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04]))

In [6]:
x.exp() - x, x.exp() + x, x.exp() * x, x.exp() / x, x**2 / x

(tensor([1.0000e+00, 1.7183e+00, 5.3891e+00, 1.7086e+01, 5.0598e+01, 1.4341e+02,
         3.9743e+02, 1.0896e+03, 2.9730e+03, 8.0941e+03, 2.2016e+04, 5.9863e+04]),
 tensor([1.0000e+00, 3.7183e+00, 9.3891e+00, 2.3086e+01, 5.8598e+01, 1.5341e+02,
         4.0943e+02, 1.1036e+03, 2.9890e+03, 8.1121e+03, 2.2036e+04, 5.9885e+04]),
 tensor([0.0000e+00, 2.7183e+00, 1.4778e+01, 6.0257e+01, 2.1839e+02, 7.4207e+02,
         2.4206e+03, 7.6764e+03, 2.3848e+04, 7.2928e+04, 2.2026e+05, 6.5862e+05]),
 tensor([       inf, 2.7183e+00, 3.6945e+00, 6.6952e+00, 1.3650e+01, 2.9683e+01,
         6.7238e+01, 1.5666e+02, 3.7262e+02, 9.0034e+02, 2.2026e+03, 5.4431e+03]),
 tensor([nan,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]))

In [7]:
r = torch.randn(3, 4)
r[1:3, 1:3] = 0.5555
r

tensor([[ 0.5517,  0.1404,  0.9459, -0.1416],
        [ 1.1432,  0.5555,  0.5555,  2.2577],
        [-1.2579,  0.5555,  0.5555, -0.3569]])

In [8]:
X + r, X * r

(tensor([[ 0.5517,  1.1404,  2.9459,  2.8584],
         [ 5.1432,  5.5555,  6.5555,  9.2577],
         [ 6.7421,  9.5555, 10.5555, 10.6431]]),
 tensor([[  0.0000,   0.1404,   1.8918,  -0.4248],
         [  4.5726,   2.7775,   3.3330,  15.8042],
         [-10.0635,   4.9995,   5.5550,  -3.9259]]))

In [9]:
torch.concat([X, r], axis=0), torch.concat([X, r], axis=1)

(tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
         [ 4.0000,  5.0000,  6.0000,  7.0000],
         [ 8.0000,  9.0000, 10.0000, 11.0000],
         [ 0.5517,  0.1404,  0.9459, -0.1416],
         [ 1.1432,  0.5555,  0.5555,  2.2577],
         [-1.2579,  0.5555,  0.5555, -0.3569]]),
 tensor([[ 0.0000,  1.0000,  2.0000,  3.0000,  0.5517,  0.1404,  0.9459, -0.1416],
         [ 4.0000,  5.0000,  6.0000,  7.0000,  1.1432,  0.5555,  0.5555,  2.2577],
         [ 8.0000,  9.0000, 10.0000, 11.0000, -1.2579,  0.5555,  0.5555, -0.3569]]))

In [10]:
X.sum(axis=0), X.sum(axis=1), X.sum()

(tensor([12, 15, 18, 21]), tensor([ 6, 22, 38]), tensor(66))

In [11]:
a = torch.arange(3)
b = torch.arange(3).reshape(3, 1)

a > b, a < b, a == b

(tensor([[False,  True,  True],
         [False, False,  True],
         [False, False, False]]),
 tensor([[False, False, False],
         [ True, False, False],
         [ True,  True, False]]),
 tensor([[ True, False, False],
         [False,  True, False],
         [False, False,  True]]))

In [12]:
print(id(X))
X = X + 0
print(id(X))
X[:] = X + 0
print(id(X))

140588136695920
140582221898896
140582221898896


In [13]:
X_np = X.numpy()
X[1, 1] = 99
X_np[2, 2] = 77

X_np, X

(array([[ 0,  1,  2,  3],
        [ 4, 99,  6,  7],
        [ 8,  9, 77, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4, 99,  6,  7],
         [ 8,  9, 77, 11]]))

In [14]:
X_np = X.numpy()
X[1, 1] = 99
X_np[2, 2] = 77

X_np, X

(array([[ 0,  1,  2,  3],
        [ 4, 99,  6,  7],
        [ 8,  9, 77, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4, 99,  6,  7],
         [ 8,  9, 77, 11]]))

In [15]:
nx = np.arange(12)
t_n = torch.from_numpy(nx).to('cuda')

nx[4] = 99
t_n[5] = 77

t_n, nx

(tensor([ 0,  1,  2,  3,  4, 77,  6,  7,  8,  9, 10, 11], device='cuda:0'),
 array([ 0,  1,  2,  3, 99,  5,  6,  7,  8,  9, 10, 11]))

# Datasets

In [19]:
ds = datasets.load_iris()

X = pd.DataFrame(data=ds.data, columns=ds.feature_names)
y = pd.DataFrame(data=ds.target, columns=['target'], dtype='category')
y.target = y.target.cat.rename_categories(ds.target_names)

X = torch.tensor(X.to_numpy())
y = torch.tensor(y.target.cat.codes)

X[:10], y[:10]

(tensor([[5.1000, 3.5000, 1.4000, 0.2000],
         [4.9000, 3.0000, 1.4000, 0.2000],
         [4.7000, 3.2000, 1.3000, 0.2000],
         [4.6000, 3.1000, 1.5000, 0.2000],
         [5.0000, 3.6000, 1.4000, 0.2000],
         [5.4000, 3.9000, 1.7000, 0.4000],
         [4.6000, 3.4000, 1.4000, 0.3000],
         [5.0000, 3.4000, 1.5000, 0.2000],
         [4.4000, 2.9000, 1.4000, 0.2000],
         [4.9000, 3.1000, 1.5000, 0.1000]], dtype=torch.float64),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int8))

## Linear Algebra

In [7]:
x, y = torch.arange(3), torch.arange(3)
x * y, x.dot(y), torch.dot(x, y), x @ y

(tensor([0, 1, 4]), tensor(5), tensor(5), tensor(5))

In [26]:
A = torch.arange(9).reshape(3, 3)

A, A@x, A.mv(x), x@A

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([ 5, 14, 23]),
 tensor([ 5, 14, 23]),
 tensor([15, 18, 21]))

In [27]:
A.sum(axis=1), A.sum(axis=1, keepdims=True), A / A.sum(axis=1), A / A.sum(axis=1, keepdims=True)

(tensor([ 3, 12, 21]),
 tensor([[ 3],
         [12],
         [21]]),
 tensor([[0.0000, 0.0833, 0.0952],
         [1.0000, 0.3333, 0.2381],
         [2.0000, 0.5833, 0.3810]]),
 tensor([[0.0000, 0.3333, 0.6667],
         [0.2500, 0.3333, 0.4167],
         [0.2857, 0.3333, 0.3810]]))

In [57]:
torch.linalg.norm(t.double()), t.double().norm(), (t**2).sum().sqrt()

(tensor(65.7571, dtype=torch.float64),
 tensor(65.7571, dtype=torch.float64),
 tensor(65.7571))

In [77]:
A = torch.randn(2**10, 2**16).to('cuda')
B = torch.randn(2**16, 2**5).to('cuda')
C = torch.randn(2**5, 2**16).to('cuda')

In [88]:
%%time
A@B

CPU times: user 279 μs, sys: 0 ns, total: 279 μs
Wall time: 210 μs


tensor([[ 122.4912, -329.9866, -660.7527,  ..., -222.6962, -328.4017,
           20.1869],
        [  83.6425, -128.4705,  -86.1336,  ...,   88.8980,  160.5203,
          116.6267],
        [-348.3337,   31.0333, -133.8974,  ...,   44.5195, -375.0338,
            9.7773],
        ...,
        [-102.9866, -318.9399,    9.9577,  ...,   17.7675,  328.0702,
           36.2171],
        [  21.4042,   30.6871, -148.0331,  ...,  415.7370, -694.0261,
          206.8282],
        [ 123.0890, -493.9423, -340.3382,  ...,  -49.2932,  184.6404,
         -116.7454]], device='cuda:0')

In [90]:
%%time
A@C.T

CPU times: user 139 μs, sys: 0 ns, total: 139 μs
Wall time: 134 μs


tensor([[-166.8682,  388.1326,  -35.6865,  ..., -277.5088, -285.0313,
         -227.4763],
        [-158.1438,  189.0386, -177.6631,  ...,  100.5351,  529.1157,
         -127.5120],
        [ -17.1950,  422.6987,  -69.8127,  ..., -433.6981,  191.6545,
          338.6786],
        ...,
        [ 326.4403, -206.2036,  341.9270,  ..., -164.0471, -184.0267,
          183.1534],
        [  31.7391,   62.9616,  464.5724,  ...,  -72.6045,    2.1875,
          187.6327],
        [ -52.4271,  201.6768,  -10.8927,  ..., -240.9334, -126.2200,
         -167.4198]], device='cuda:0')